### PR TITLE
Handle true/false as booleans

### PR DESCRIPTION
**Pull request by szepeviktor**

### CODE REVIEW

**Comment by MickeyKay** [comment]
Hi @szepeviktor. Can you please provide some context on this PR? What's the problem you're seeking to solve?

**Comment by szepeviktor** [comment]
It makes 1 line from 5 as `is_readable` already returns a boolean.

**Comment by MickeyKay** [comment]
Is there a specific problem this solves? I see tests are now failing, and I wouldn't have thought that this should functionally change anything. Can you please run tests locally and fix and issues? `npm run develop && npm run test` should get you what you need.

**Comment by szepeviktor** [comment]
> Can you please run tests locally and fix and issues?

PHPCS find that `better-font-awesome.php` is not written in WPCS.
This has nothing to do with this PR.

**Pull request closed without merging**
